#ifndef LPTIM_H_INCLUDED
#define LPTIM_H_INCLUDED

#define LPTIM_SYNC_CLOCKS 2

#define LPTIM_ISR 0x00
#define LPTIM_ICR 0x04
#define LPTIM_IER 0x08
#define LPTIM_CFGR 0x0C
#define LPTIM_CR 0x10
#define LPTIM_CMP 0x14
#define LPTIM_ARR 0x18
#define LPTIM_CNT 0x1C

#define LPTIM_ENABLE_S 0
#define LPTIM_ENABLE_M (1 << LPTIM_ENABLE_S)
#define LPTIM_DISABLE_M (0 << LPTIM_ENABLE_S)
#define LPTIM_START_SINGLE_MODE_S 1
#define LPTIM_START_SINGLE_MODE_M (1 << LPTIM_START_SINGLE_MODE_S)
#define LPTIM_START_CONTIN_MODE_S 2
#define LPTIM_START_CONTIN_MODE_M (1 << LPTIM_START_CONTIN_MODE_S)

#define LPTIM_PRESCALER_S 9
#define LPTIM_PRESCALER_1_M (0x0 << LPTIM_PRESCALER_S)
#define LPTIM_PRESCALER_2_M (0x1 << LPTIM_PRESCALER_S)
#define LPTIM_PRESCALER_4_M (0x2 << LPTIM_PRESCALER_S)
#define LPTIM_PRESCALER_8_M (0x3 << LPTIM_PRESCALER_S)
#define LPTIM_PRESCALER_16_M (0x4 << LPTIM_PRESCALER_S)
#define LPTIM_PRESCALER_32_M (0x5 << LPTIM_PRESCALER_S)
#define LPTIM_PRESCALER_64_M (0x6 << LPTIM_PRESCALER_S)
#define LPTIM_PRESCALER_128_M (0x7 << LPTIM_PRESCALER_S)

// Alias for CFGR.ENC bit
#define LPTIM_ENCODER_S 24
#define LPTIM_ENCODER_DISABLE_M (0x0 << LPTIM_ENCODER_S)
#define LPTIM_ENCODER_ENABLE_M (0x1 << LPTIM_ENCODER_S)

#define LPTIM_INT_CMP_MATCH_S 0
#define LPTIM_INT_CMP_MATCH_M (0x1 << LPTIM_INT_CMP_MATCH_S)
#define LPTIM_INT_ARR_MATCH_S 1
#define LPTIM_INT_ARR_MATCH_M (0x1 << LPTIM_INT_ARR_MATCH_S)
#define LPTIM_INT_EXT_TRIG_S 2
#define LPTIM_INT_EXT_TRIG_M (0x1 << LPTIM_INT_EXT_TRIG_S)
#define LPTIM_INT_CMP_OK_S 3
#define LPTIM_INT_CMP_OK_M (0x1 << LPTIM_INT_CMP_OK_S)
#define LPTIM_INT_ARR_OK_S 4
#define LPTIM_INT_ARR_OK_M (0x1 << LPTIM_INT_ARR_OK_S)
#define LPTIM_INT_UP_S 5
#define LPTIM_INT_UP_M (0x1 << LPTIM_INT_UP_S)
#define LPTIM_INT_DOWN_S 6
#define LPTIM_INT_DOWN_M (0x1 << LPTIM_INT_DOWN_S)

#define LPTIM_CFGR_ENC_S 24
#define LPTIM_CFGR_ENC_M (1 << LPTIM_CFGR_ENC_S)
#define LPTIM_CFGR_COUNTMODE_S 23
#define LPTIM_CFGR_COUNTMODE_M (1 << LPTIM_CFGR_COUNTMODE_S)
#define LPTIM_CFGR_PRELOAD_S 22
#define LPTIM_CFGR_PRELOAD_M (1 << LPTIM_CFGR_PRELOAD_S)
#define LPTIM_CFGR_WAVPOL_S 21
#define LPTIM_CFGR_WAVPOL_M (1 << LPTIM_CFGR_WAVPOL_S)
#define LPTIM_CFGR_WAVE_S 20
#define LPTIM_CFGR_WAVE_M (1 << LPTIM_CFGR_WAVE_S)
#define LPTIM_CFGR_TIMOUT_S 19
#define LPTIM_CFGR_TIMOUT_M (1 << LPTIM_CFGR_TIMOUT_S)
#define LPTIM_CFGR_TRIGEN_S 17
#define LPTIM_CFGR_TRIGEN_M (0x3 << LPTIM_CFGR_TRIGEN_S)
//
#define LPTIM_CFGR_TRIGSEL_S 13
#define LPTIM_CFGR_TRIGSEL_M (0x7 << LPTIM_CFGR_TRIGSEL_S)
//
#define LPTIM_CFGR_TRGFLT_S 6
#define LPTIM_CFGR_TRGFLT_M (0x3 << LPTIM_CFGR_TRGFLT_S)
#define LPTIM_CFGR_TRGFLT_DISABLED_M (0x0 << LPTIM_CFGR_TRGFLT_S)
#define LPTIM_CFGR_TRGFLT_2_M (0x1 << LPTIM_CFGR_TRGFLT_S)
#define LPTIM_CFGR_TRGFLT_4_M (0x2 << LPTIM_CFGR_TRGFLT_S)
#define LPTIM_CFGR_TRGFLT_8_M (0x3 << LPTIM_CFGR_TRGFLT_S)
#define LPTIM_CFGR_CKFLT_S 3
#define LPTIM_CFGR_CKFLT_M (0x3 << LPTIM_CFGR_CKFLT_S)
#define LPTIM_CFGR_CKFLT_DISABLED_M (0x0 << LPTIM_CFGR_CKFLT_S)
#define LPTIM_CFGR_CKFLT_2_M (0x1 << LPTIM_CFGR_CKFLT_S)
#define LPTIM_CFGR_CKFLT_4_M (0x2 << LPTIM_CFGR_CKFLT_S)
#define LPTIM_CFGR_CKFLT_8_M (0x3 << LPTIM_CFGR_CKFLT_S)
#define LPTIM_CFGR_CKPOL_S 1
#define LPTIM_CFGR_CKPOL_M (0x3 << LPTIM_CFGR_CKPOL_S)
#define LPTIM_CFGR_CKPOL_RISING_M (0x0 << LPTIM_CFGR_CKPOL_S)
#define LPTIM_CFGR_CKPOL_FALLING_M (0x1 << LPTIM_CFGR_CKPOL_S)
#define LPTIM_CFGR_CKPOL_ANY_M (0x2 << LPTIM_CFGR_CKPOL_S)
#define LPTIM_CFGR_CKSEL_S 0
#define LPTIM_CFGR_CKSEL_M (1 << LPTIM_CFGR_CKSEL_S)
#define LPTIM_CFGR_CKSEL_INTERNAL_M (0x0 << LPTIM_CFGR_CKSEL_S)
#define LPTIM_CFGR_CKSEL_EXTERNAL_M (0x1 << LPTIM_CFGR_CKSEL_S)

#ifndef _ASSEMBLER_
#include <inttypes.h>

typedef struct
{
    volatile uint32_t ISR;
    volatile uint32_t ICR;
    volatile uint32_t IER;
    volatile uint32_t CFGR;
    volatile uint32_t CR;
    volatile uint32_t CMP;
    volatile uint32_t ARR;
    volatile uint32_t CNT;

} LPTIM_TypeDef;
#endif

#endif // LPTIM_H_INCLUDED
