#ifndef MCU32_MEMORY_MAP_H_INCLUDED
#define MCU32_MEMORY_MAP_H_INCLUDED

#define EEPROM_BASE_ADDRESS 0x01000000
#define EEPROM_SIZE (16 * 1024)

#define RAM_BASE_ADDRESS 0x02000000
#define RAM_SIZE (16 * 1024)

#define SPIFI_BASE_ADDRESS 0x80000000
#define SPIFI_SIZE (2 * 1024 * 1024)

#define BOOT_BASE_ADDRESS 0x00000000
#define BOOT_SIZE (16 * 1024)

#define APB_PERIPH_STEP 0x00000400

#define DMA_CONFIG_BASE_ADDRESS 0x000040000

#define APB_DOM_0_BASE_ADDRESS 0x000050000
#define PM_BASE_ADDRESS 0x000050000
#define EPIC_BASE_ADDRESS 0x000050400
#define TIM0_BASE_ADDRESS 0x000050800
#define PAD_CONFIG_BASE_ADDRESS 0x000050c00
#define WDT_BUS_BASE_ADDRESS 0x000051000
#define OTP_BASE_ADDRESS 0x000051400
#define PVD_CONTROL_BASE_ADDRESS 0x000051800

#define WU_BASE_ADDRESS 0x00060000
#define RTC_BASE_ADDRESS 0x00060400
#define BOOT_MANAGER_BASE_ADDRESS 0x00060800

#define SPIFI_ADDRESS 0x00070000
#define EEPROM_REGS_BASE_ADDRESS 0x00070400
#define CRYPTO_BASE_ADDRESS 0x00080000
#define CRC_BASE_ADDRESS 0x00080400

#define APB_DOM_3_BASE_ADDRESS 0x00081000

#define WDT_BASE_ADDRESS 0x00081000
#define UART0_BASE_ADDRESS 0x00081400
#define UART1_BASE_ADDRESS 0x00081800
#define LPTIM0_BASE_ADDRESS 0x00081C00
#define LPTIM1_BASE_ADDRESS 0x00082000
#define LPTIM2_BASE_ADDRESS 0x00082400
#define TIM1_BASE_ADDRESS 0x00082800
#define TIM2_BASE_ADDRESS 0x00082C00
#define SPI0_BASE_ADDRESS 0x00083000
#define SPI1_BASE_ADDRESS 0x00083400
#define I2C0_BASE_ADDRESS 0x00083800
#define I2C1_BASE_ADDRESS 0x00083C00
#define GPIO0_BASE_ADDRESS 0x00084000
#define GPIO1_BASE_ADDRESS 0x00084400
#define GPIO2_BASE_ADDRESS 0x00084800
#define GPIO_IRQ_BASE_ADDRESS 0x00084C00
#define ADC_BASE_ADDRESS 0x00085000

#define SCR1_TIMER_BASE_ADDRESS 0x00490000

#define DMA_CONFIG ((DMA_CONFIG_TypeDef*)DMA_CONFIG_BASE_ADDRESS)

#define PM ((PM_TypeDef*)PM_BASE_ADDRESS)
#define EPIC ((EPIC_TypeDef*)EPIC_BASE_ADDRESS)
#define TIM0 ((TIM_TypeDef*)TIM0_BASE_ADDRESS)
#define PVD_CONTROL ((PVD_CONTROL_TypeDef*)PVD_CONTROL_BASE_ADDRESS)
#define PAD_CONFIG ((PAD_CONFIG_TypeDef*)PAD_CONFIG_BASE_ADDRESS)
#define WDT_BUS ((WDT_BUS_TypeDef*)WDT_BUS_BASE_ADDRESS)
#define OTP ((OTP_TypeDef*)OTP_BASE_ADDRESS)

#define WU ((WU_TypeDef*)WU_BASE_ADDRESS)
#define RTC ((RTC_TypeDef*)RTC_BASE_ADDRESS)
#define BOOT_MANAGER ((BOOT_MANAGER_TypeDef*)BOOT_MANAGER_BASE_ADDRESS)

#define SPIFI ((SPIFI_TypeDef*)SPIFI_ADDRESS)
#define EEPROM_REGS ((EEPROM_REGS_TypeDef*)EEPROM_REGS_BASE_ADDRESS)
#define CRYPTO ((CRYPTO_TypeDef*)CRYPTO_BASE_ADDRESS)
#define CRC ((CRC_TypeDef*)CRC_BASE_ADDRESS)

#define WDT ((WDT_TypeDef*)WDT_BASE_ADDRESS)
#define UART0 ((UART_TypeDef*)UART0_BASE_ADDRESS)
#define UART1 ((UART_TypeDef*)UART1_BASE_ADDRESS)
#define LPTIM0 ((LPTIM_TypeDef*)LPTIM0_BASE_ADDRESS)
#define LPTIM1 ((LPTIM_TypeDef*)LPTIM1_BASE_ADDRESS)
#define LPTIM2 ((LPTIM_TypeDef*)LPTIM2_BASE_ADDRESS)
#define TIM1 ((TIM_TypeDef*)TIM1_BASE_ADDRESS)
#define TIM2 ((TIM_TypeDef*)TIM2_BASE_ADDRESS)
#define SPI0 ((SPI_TypeDef*)SPI0_BASE_ADDRESS)
#define SPI1 ((SPI_TypeDef*)SPI1_BASE_ADDRESS)
#define I2C0 ((I2C_TypeDef*)I2C0_BASE_ADDRESS)
#define I2C1 ((I2C_TypeDef*)I2C1_BASE_ADDRESS)
#define GPIO0 ((GPIO_TypeDef*)GPIO0_BASE_ADDRESS)
#define GPIO1 ((GPIO_TypeDef*)GPIO1_BASE_ADDRESS)
#define GPIO2 ((GPIO_TypeDef*)GPIO2_BASE_ADDRESS)
#define GPIO_IRQ ((GPIO_IRQ_TypeDef*)GPIO_IRQ_BASE_ADDRESS)
#define ADC ((ADC_TypeDef*)ADC_BASE_ADDRESS)

#define SCR1_TIMER ((SCR1_TIMER_TypeDef*)SCR1_TIMER_BASE_ADDRESS)

//
// Clock gating masks to be used with PM module
// AHB BUS
#define PM_CLOCK_CPU_BIT 0
#define PM_CLOCK_EEPROM_BIT 1
#define PM_CLOCK_RAM_BIT 2
#define PM_CLOCK_SPIFI_BIT 3
#define PM_CLOCK_TCB_BIT 4
#define PM_CLOCK_DMA_BIT 5
#define PM_CLOCK_CRYPTO_BIT 6
#define PM_CLOCK_CRC32_BIT 7

#define PM_CLOCK_CPU (1 << PM_CLOCK_CPU_BIT)
#define PM_CLOCK_EEPROM (1 << PM_CLOCK_EEPROM_BIT)
#define PM_CLOCK_RAM (1 << PM_CLOCK_RAM_BIT)
#define PM_CLOCK_SPIFI (1 << PM_CLOCK_SPIFI_BIT)
#define PM_CLOCK_TCB (1 << PM_CLOCK_TCB_BIT)
#define PM_CLOCK_DMA (1 << PM_CLOCK_DMA_BIT)
#define PM_CLOCK_CRYPTO (1 << PM_CLOCK_CRYPTO_BIT)
#define PM_CLOCK_CRC32 (1 << PM_CLOCK_CRC32_BIT)

// APB M BUS
#define PM_CLOCK_PM_BIT 0
#define PM_CLOCK_EPIC_BIT 1
#define PM_CLOCK_TIM0_BIT 2
#define PM_CLOCK_PAD_CONFIG_BIT 3
#define PM_CLOCK_WDT_BUS_BIT 4
#define PM_CLOCK_OTP_CONTROLLER_BIT 5
#define PM_CLOCK_PVD_CONTROL_BIT 6
#define PM_CLOCK_WU_BIT 7
#define PM_CLOCK_RTC_BIT 8

#define PM_CLOCK_PM (1 << PM_CLOCK_PM_BIT)
#define PM_CLOCK_EPIC (1 << PM_CLOCK_EPIC_BIT)
#define PM_CLOCK_TIM0 (1 << PM_CLOCK_TIM0_BIT)
#define PM_CLOCK_PAD_CONFIG (1 << PM_CLOCK_PAD_CONFIG_BIT)
#define PM_CLOCK_WDT_BUS (1 << PM_CLOCK_WDT_BUS_BIT)
#define PM_CLOCK_OTP_CONTROLLER (1 << PM_CLOCK_OTP_CONTROLLER_BIT)
#define PM_CLOCK_PVD_CONTROL (1 << PM_CLOCK_PVD_CONTROL_BIT)
#define PM_CLOCK_WU (1 << PM_CLOCK_WU_BIT)
#define PM_CLOCK_RTC (1 << PM_CLOCK_RTC_BIT)

// APB P BUS
#define PM_CLOCK_WDT_BIT 0
#define PM_CLOCK_UART0_BIT 1
#define PM_CLOCK_UART1_BIT 2
#define PM_CLOCK_LPTIM0_BIT 3
#define PM_CLOCK_LPTIM1_BIT 4
#define PM_CLOCK_LPTIM2_BIT 5

#define PM_CLOCK_WDT (1 << PM_CLOCK_WDT_BIT)
#define PM_CLOCK_UART0 (1 << PM_CLOCK_UART0_BIT)
#define PM_CLOCK_UART1 (1 << PM_CLOCK_UART1_BIT)
#define PM_CLOCK_LPTIM0 (1 << PM_CLOCK_LPTIM0_BIT)
#define PM_CLOCK_LPTIM1 (1 << PM_CLOCK_LPTIM1_BIT)
#define PM_CLOCK_LPTIM2 (1 << PM_CLOCK_LPTIM2_BIT)
//
#define PM_CLOCK_TIM1_BIT 6
#define PM_CLOCK_TIM2_BIT 7
#define PM_CLOCK_SPI0_BIT 8
#define PM_CLOCK_SPI1_BIT 9
#define PM_CLOCK_I2C0_BIT 10
#define PM_CLOCK_I2C1_BIT 11
#define PM_CLOCK_GPIO0_BIT 12
#define PM_CLOCK_GPIO1_BIT 13
#define PM_CLOCK_GPIO2_BIT 14
#define PM_CLOCK_ADC_BIT 15
#define PM_CLOCK_GPIO_IRQ_BIT 16

#define PM_CLOCK_TIM1 (1 << PM_CLOCK_TIM1_BIT)
#define PM_CLOCK_TIM2 (1 << PM_CLOCK_TIM2_BIT)
#define PM_CLOCK_SPI0 (1 << PM_CLOCK_SPI0_BIT)
#define PM_CLOCK_SPI1 (1 << PM_CLOCK_SPI1_BIT)
#define PM_CLOCK_I2C0 (1 << PM_CLOCK_I2C0_BIT)
#define PM_CLOCK_I2C1 (1 << PM_CLOCK_I2C1_BIT)
#define PM_CLOCK_GPIO0 (1 << PM_CLOCK_GPIO0_BIT)
#define PM_CLOCK_GPIO1 (1 << PM_CLOCK_GPIO1_BIT)
#define PM_CLOCK_GPIO2 (1 << PM_CLOCK_GPIO2_BIT)
#define PM_CLOCK_ADC (1 << PM_CLOCK_ADC_BIT)
#define PM_CLOCK_GPIO_IRQ (1 << PM_CLOCK_GPIO_IRQ_BIT)

// Timer connection to PM multiplexor controling timer inputs
//
#define PM_TIM0_INDEX 0
#define PM_TIM1_INDEX 1
#define PM_TIM2_INDEX 2
#define PM_LPTIM0_INDEX 3
#define PM_LPTIM1_INDEX 4
#define PM_LPTIM2_INDEX 5

//
// Interrupt lines to be used with EPIC module
//

#define EPIC_TIM0_INDEX 0

#define EPIC_UART0_INDEX 1
#define EPIC_UART1_INDEX 2
#define EPIC_SPI0_INDEX 3
#define EPIC_SPI1_INDEX 4
#define EPIC_GPIO_IRQ_INDEX 5
#define EPIC_I2C0_INDEX 6
#define EPIC_I2C1_INDEX 7
#define EPIC_WDT_INDEX 8
#define EPIC_LPTIM0_INDEX 9
#define EPIC_LPTIM1_INDEX 10
#define EPIC_LPTIM2_INDEX 11
#define EPIC_TIM1_INDEX 12
#define EPIC_TIM2_INDEX 13
#define EPIC_SPIFI_INDEX 14
#define EPIC_RTC_INDEX 15
#define EPIC_EEPROM_INDEX 16
#define EPIC_WDT_DOM3_INDEX 17
#define EPIC_WDT_SPIFI_INDEX 18
#define EPIC_WDT_EEPROM_INDEX 19
#define EPIC_DMA_GLB_ERR_INDEX 20
#define EPIC_DMA_CHANNELS_INDEX 21
#define EPIC_FREQ_MON_INDEX 22
#define EPIC_PVD_AVCC_UNDER 23
#define EPIC_PVD_AVCC_OVER 24
#define EPIC_PVD_VCC_UNDER 25
#define EPIC_PVD_VCC_OVER 26
#define EPIC_BATTERY_NON_GOOD 27

#define EPIC_BOR_INDEX 28
#define EPIC_TSENS_INDEX 29
#define EPIC_ADC_INDEX 30

// DMA request lines
//
#define DMA_UART0_INDEX 0
#define DMA_UART1_INDEX 1
#define DMA_CRYPTO_INDEX 2
#define DMA_SPI0_INDEX 3
#define DMA_SPI1_INDEX 4
#define DMA_I2C0_INDEX 5
#define DMA_I2C1_INDEX 6
#define DMA_SPIFI_INDEX 7
#define DMA_TIM1_INDEX 8
#define DMA_TIM2_INDEX 9
#define DMA_TIM0_INDEX 10

#endif // MCU32_MEMORY_MAP_H_INCLUDED
